### PR TITLE
Add JS and JSX syntax definition

### PR DESCRIPTION
**Pull request by zertosh**
This PR pretty much sets everything up. This is the interesting stuff: https://github.com/6to5/6to5-sublime/compare/4333fb8...8be8583. There are a few issues/todos that need to get figured out before we "launch".

* [x] Make screenshots showing ES6+JSX
* [x] Pick a Package Control name (see restrictions https://packagecontrol.io/docs/submitting_a_package#Step_2)
* [x] Fill out the `README.md` (I'll do this once we have a name)
* [x] License to Andres Suarez or 6to5 org? Is that a thing?

cc: @sebmck @Dashed (who else should I tag?)

EDIT: I think the package should be called "6to5 JavaScript JSX Syntax"

### CODE REVIEW

**Comment by Dashed** [comment]
Do you have a Package Control name in mind?

Looking over some names in https://packagecontrol.io/browse/labels/language%20syntax
it seems safe to just call it **6to5**. 

----

In a few days, I want to try and test drive this syntax theme :smile:

**Comment by sebmck** [comment]
Yeah, this is looking to be really awesome and is sorely needed. Flow type support would also be awesome. For the record, I'm completely fine with the 6to5 suggestion by @Dashed.

**Comment by zertosh** [comment]
Cool, I dig the "6to5" name. I'll try to get that out the door tonight.

**Comment by zertosh** [comment]
Hey @sebmck, we set repo description to something? I submitted the Package Control description as "Syntax definitions for ES6 JavaScript with React JSX extensions" - so how about that?

**Comment by zertosh** [comment]
Now we wait... https://github.com/wbond/package_control_channel/pull/3998

**Comment by sebmck** [comment]
@zertosh Sure. Feel free to make all decisions on your own, this is your project/repo after all!

**Comment by zertosh** [comment]
@sebmck I don't think I have the permissions to do it since I don't see the usual "Edit" button below the repo name :/

**Comment by sebmck** [comment]
@zertosh What about now?

**Comment by zertosh** [comment]
@sebmck nope

**Comment by sebmck** [comment]
@zertosh Woops, accidently set the permissions on the wrong team. You should be able to now.

**Comment by zertosh** [comment]
@sebmck works now! thanks! one last thing: how do you feel about a blog post? (For release on Tuesday for max effect since Monday is a holiday in the US) I can submit a PR for it in https://github.com/6to5/6to5.github.io

**Comment by sebmck** [comment]
@zertosh Sure, I don't see a problem with it. @thejameskyle handles most of the website/blog stuff. @thejameskyle What do you think?

**Comment by Dashed** [comment]
@zertosh @sebmck Off-topic suggestion: I think it'll be awesome if there's also an Atom editor syntax theme. I think TextMate grammar convention is also being used for Atom syntax themes.

AFAIK these are the ES6/JSX options in Atom:
https://github.com/atom/language-javascript
https://github.com/orktes/atom-react

**Comment by sebmck** [comment]
@Dashed Atom supports the textmate snippets/syntax format so this should already work. Would be a good idea to package it up for it though.

**Comment by zertosh** [comment]
@Dashed I don't know how it works with Atom (I'm not a user) - but I'll certainly look into it

**Comment by zertosh** [comment]
@sebmck @Dashed: sorry for all the noise, but WE'RE LIVE! go install `6to5` :smiley:

**Comment by Dashed** [comment]
Yep. Just installed it now :smile: 

----

@zertosh I was suggesting the Atom syntax theme so that the blog announcement can have a "bigger" reach/impact. I'm not really an Atom user either.

**Comment by thejameskyle** [comment]
If you want to write a quick blog post I'll review it and publish it whenever you want.

Blog posts go [here](https://github.com/6to5/6to5.github.io/tree/master/_posts) if you want to make a PR, make sure you have the correct front matter as seen [here](https://raw.githubusercontent.com/6to5/6to5.github.io/master/_posts/2015-01-12-6to5-esnext.md).

**Comment by zertosh** [comment]
@thejameskyle Took me a while but here it is https://github.com/6to5/6to5.github.io/pull/69. I'm open to any and all critiques.

**Comment by sebmck** [comment]
I think having an atom package would be a good idea if someone is willing to take it on. Seems to be a pretty easy conversion, just run a couple commands: https://atom.io/docs/v0.60.0/converting-a-text-mate-bundle @Dashed Would you be interested?

**Comment by Dashed** [comment]
I might be interested. But I wouldn't be doing it soon. TextMate language stuff still confuse me. :stuck_out_tongue: 

I was only briefly interested in Atom when 6to5-sublime/babel-sublime didn't exist, since there weren't any decent JSX + ES6+ highlighting for sublime.

**Comment by zertosh** [comment]
Let add some of my findings from attempting an Atom port:

1. [Atom grammars](https://atom.io/docs/latest/creating-a-package#language-grammars) use a Textmate "compatible" language schema - just like Sublime. I don't know how "compatible" is "compatible".
2. For a file format, Atom uses [CSON](https://github.com/bevry/cson) (though JSON works too) while Sublime uses Plist.
   * Since we use YAML and since [AAAPackageDev](https://github.com/SublimeText/AAAPackageDev) is the shit, it's trivial to output JSON:
   * In the `JavaScript (Babel).YAML-tmLanguage` file, just change `# [PackageDev] target_format: plist, ext: tmLanguage` to `# [PackageDev] target_format: json, ext: json`, and Build!
3. To get a package into Atom:
   * Run `apm init -l whateverName` to create the scaffolding (just like `npm init`),
   * Then, from that dir run `apm link` (just like `npm link`),
   * And, now you have `whateverName` linked to Atom and you can start using it.
4. I did all this, and that's where it stopped working with this error:
fkcxz
   * That error comes up over and over.
   * I thought it had something to do with the `$self` recursion, but I saw other grammars do it.

And this is where I stopped.

**Comment by zertosh** [comment]
Additional note: I thought that maybe the problem was the use of look-behinds (since JS doesn't support them), but it turned out that Atom uses [node-oniguruma](https://github.com/atom/node-oniguruma) to do the grammar regexp matching - so that's not it.

**Comment by Dashed** [comment]
I reproduced steps to make the atom package, and saw the same errors. The error seems to be for every single line in the JS file. 

It may be the fact that everything is tucked into `repository`?

These are issues with similar errors: 
- https://github.com/atom/first-mate/issues/11 
- https://github.com/matthojo/language-stylus/issues/1

Maybe we should file an issue at https://github.com/atom/first-mate

**Comment by zertosh** [comment]
"...It turned out that it was a duplicate Regex and was causing an infinite loop..." - https://github.com/matthojo/language-stylus/issues/1#issuecomment-37232140. I wonder if the regexp engine is getting tripped up by lookarounds and treating assertions as part of the match.

**Comment by Dashed** [comment]
By the way, did you get any highlighting? I got some highlighting despite the errors.

**Comment by zertosh** [comment]
I got a bit of highlighting. If you inspect the individual nodes, the correctly colored ones got class names that match the syntax rule's scope selector - so that's encouraging.

**Comment by Dashed** [comment]
I notice that functions and parameters aren't highlighted: `foo(bar);`

I'm using the following themes to compare sublime and atom:
https://github.com/voronianski/oceanic-next-theme
https://atom.io/themes/oceanic-next

------

This wouldn't be a trivial port. I don't know how to debug this :sweat:.

**Comment by zertosh** [comment]
I was thinking to maybe start with zero rules, and slowly start adding them until the error came up - then take it from there.

**Comment by gyzerok** [comment]
I'd be glad to help you getting it works for atom if possible.

**Comment by johanneslumpe** [comment]
Are there any news on this? @zertosh Did you take another look at this?

**Comment by zertosh** [comment]
I'm going to hold off a bit to see what http://nuclide.io/ turns up with. When I was watching the announcement, I think I noticed that they were using the stock javascript syntax - but I don't know.

**Comment by johanneslumpe** [comment]
Ok cool. Thanks for providing that link - didn't know about it before, surely looks interesting!

**Comment by Dashed** [comment]
Woah. I didn't know about nuclide. I hope the performance issues are addressed :D

**Comment by Shenlok** [comment]
For what it's worth, the [language-babel](https://github.com/gandm/language-babel) Atom package provides syntax highlighting based on babel-sublime. I'm not sure exactly to what extent they match, but when using it alongside the oceanic-next syntax theme things seem nearly identical to the respective Sublime setup.

**Pull request merged**
