### PR TITLE
Add react concise component snippet

### PR DESCRIPTION
**Pull request by qmmr**
Add `rcs` snippet -> react concise component skeleton which simply exports default React.createClass.

### CODE REVIEW

**Comment by zertosh** [comment]
@qmmr Cool!

What do you think about this? If you wrap the `displayName` like this `${1:displayName: '${2:myAwesomeComponent}',}`, then you can either hit _backspace_ and remove the entire `displayName` line, or _tab_ to the component name.

Also, can you add an entry in the README's snippets chart?

**Comment by qmmr** [comment]
@zertosh good idea, however in order to avoid unnecessary tabs when one's decide not to use the `displayName`, I've switched the order. What do you think?

**Comment by zertosh** [comment]
Oh yeah that feels muchhhhh better, good call!

Sorry to be so nitpicky but you just reminded me of something else, check out https://github.com/6to5/6to5-sublime/pull/24. It's hard to tell from the diff, but those are now actual _tab_ characters used for indentation.

**Comment by qmmr** [comment]
Ha! I was about to ask if we can switch to tabs :wink: Amended.

**Pull request merged**
